---
version: "3.9"

services:
  # Postgres with the Pagila sample data set
  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/docker/postgresql/:/docker-entrypoint-initdb.d/

  trino:
    image: trinodb/trino:438
    hostname: trino_container 
    ports:
      - 8080:8080 
    volumes:
      - ${PWD}/docker/trino/catalog:/etc/trino/catalog
      - ${PWD}/docker/trino/config.properties:/etc/trino/config.properties
      - ${PWD}/docker/trino/password-authenticator.properties:/etc/trino/password-authenticator.properties
      - ${PWD}/docker/trino/password.db:/etc/trino/password.db
    depends_on:
      - hive-metastore
      - mariadb
      - minio
  
  # Hive MetaStore backed by MariaDB for Table metadata
  hive-metastore:
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083'
    volumes:
      -  ${PWD}/docker/hive/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
  mariadb:
    image: 'mariadb:10.11.2'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  
  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: ghcr.io/projectnessie/nessie:0.76.5
    ports:
      - 19120:19120

  # Minio Storage Server
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_DOMAIN: "storage"
      MINIO_REGION_NAME: "us-east-1"
      MINIO_REGION: "us-east-1"
    ports:
      - 9001:9001 # UI Access
      - 9000:9000
    command: server /data --console-address ":9001"

  # Metabase 
  # curl -kL -o /plugins/duckdb.metabase-driver.jar https://github.com/AlexR2D2/metabase_duckdb_driver/releases/download/0.2.3/duckdb.metabase-driver.jar
  metabase:
    # image: metabase/metabase:v0.48.4
    build: ./docker/metabase
    ports:
      - "5000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ${PWD}/docker/metabase/data:/metabase-data
      - ${PWD}/database.duckdb:/duckdb/database.duckdb
    