---
version: "3.9"

services:
  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/docker/postgresql/:/docker-entrypoint-initdb.d/

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/docker/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/docker/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"