version: 2

sources:
  - name: source
    database: database
    schema: main
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: film
      - name: category
      - name: film_category